---
- name: check ntp installation on redhat
  command: rpm -q ntp
  args:
    warn: no
  register: ntp_pkg_query
  ignore_errors: true
  changed_when: false
  when:
    - ansible_os_family == 'RedHat'
  tags:
    - always

- name: install ntp on redhat
  package:
    name: ntp
    state: present
